CREATE TABLE IF NOT EXISTS book (
    id bigserial PRIMARY KEY,
    created_at timestamp(0) with time zone NOT NULL DEFAULT NOW(),
    title text NOT NULL,
    description text,
    author text[],
    category text,
    publisher text,
    language text,
    series text,
    volume integer,
    edition text,
    year integer,
    page_count integer,
    isbn_10 varchar(10),
    isbn_13 varchar(13),
    cover_path text,
    s3_file_key text NOT NULL,
    additional_info jsonb NOT NULL,
    version integer NOT NULL DEFAULT 1
);